// @ts-nocheck
// Generated by Void Manifest Engine
// Get words for review (SRS)

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function GET(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Get vocabulary words due for review based on spaced repetition algorithm and learner category

  const items = await prisma.word.findMany()
  return NextResponse.json(items)
}