// @ts-nocheck
// Generated by Void Manifest Engine
// Get words for review (SRS)

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { BUILTIN_WORDS } from '@/lib/builtinWords'

export async function GET(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const userId = Number(user.sub)
  const profile = await prisma.user.findUnique({
    where: { id: userId },
    select: { nativeLanguage: true },
  })
  const legacyRussianSupport = /^(?:русский|russian)$/iu.test(profile?.nativeLanguage || '')
  await Promise.all(BUILTIN_WORDS.map(async (word) => {
    const existing = await prisma.word.findFirst({ where: { english: word.english }, select: { id: true } })
    if (!existing) {
      const { definitionEnglish: _definitionEnglish, ...storedWord } = word
      await prisma.word.create({ data: { ...storedWord, learnerCategory: 'all' } })
    }
  }))

  const items = await prisma.word.findMany({
    include: { Reviews: { where: { userId }, take: 1 } },
    orderBy: [{ difficultyLevel: 'asc' }, { id: 'asc' }],
  })
  return NextResponse.json(items.map(({ Reviews, ...word }) => ({
    ...word,
    translationNative: legacyRussianSupport
      ? word.translationNative
      : BUILTIN_WORDS.find((entry) => entry.english === word.english)?.definitionEnglish || '',
    review: Reviews[0] ?? null,
  })))
}
