// @ts-nocheck
// Generated by Void Manifest Engine
// Get lesson with exercises

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function GET(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Get lesson detail with all exercises

  const id = Number(request.nextUrl.pathname.split('/').pop() || '0')
  const item = await prisma.lesson.findUnique({ where: { id: Number(id) }, include: { Exercises: true } })
  if (!item) return NextResponse.json({ error: 'Not found' }, { status: 404 })
  return NextResponse.json(item)
}