// Generated by Void Manifest Engine
import { NextRequest } from 'next/server'
import { jwtVerify } from 'jose'

const JWT_SECRET = new TextEncoder().encode(process.env.JWT_SECRET || 'dev-secret-change-me')

export async function authenticate(request: NextRequest) {
  const token = request.headers.get('Authorization')?.replace('Bearer ', '')
  if (!token) return null
  try {
    const { payload } = await jwtVerify(token, JWT_SECRET)
    return payload as { sub: string; role: string }
  } catch {
    return null
  }
}

export function requireRole(user: any, ...roles: string[]) {
  if (!user) return false
  return roles.length === 0 || roles.includes(user.role)
}
