// Shared Mila palette. Historical semantic names remain for compatibility, but
// every interactive channel resolves to the same electric signal. Meaning comes
// from copy, iconography, and state — never from a competing accent colour.
export const C = {
  pageBg: 'var(--surface-page, transparent)',
  venus: 'var(--mila-action, #d9006c)',
  venusBright: 'var(--mila-action, #d9006c)',
  venusDeep: 'var(--mila-action-deep, #a40050)',
  venusInk: 'var(--mila-action-ink, #ffffff)',
  venusL: 'var(--mila-action-soft, rgba(217,0,108,0.12))',
  danger: 'var(--mila-danger, #a40050)',
  dangerL: 'var(--mila-danger-soft, rgba(217,0,108,0.12))',
  rose: 'var(--mila-action, #d9006c)',
  roseL: 'var(--mila-action-soft, rgba(217,0,108,0.12))',
  mercury: 'var(--mila-action, #d9006c)',
  mercuryBright: 'var(--mila-action, #d9006c)',
  mercuryDeep: 'var(--mila-action-deep, #a40050)',
  mercuryL: 'var(--mila-action-soft, rgba(217,0,108,0.12))',
  voice: 'var(--mila-action, #d9006c)',
  voiceBright: 'var(--mila-action, #d9006c)',
  voiceL: 'var(--mila-action-soft, rgba(217,0,108,0.12))',
  jupiter: 'var(--mila-action, #d9006c)',
  jupiterBright: 'var(--mila-action, #d9006c)',
  jupiterDeep: 'var(--mila-action-deep, #a40050)',
  jupiterL: 'var(--mila-action-soft, rgba(217,0,108,0.12))',
  sage: 'var(--mila-action, #d9006c)',
  sageL: 'var(--mila-action-soft, rgba(217,0,108,0.12))',
  gold: 'var(--mila-action, #d9006c)',
  goldL: 'var(--mila-action-soft, rgba(217,0,108,0.12))',
  purple: 'var(--mila-action, #d9006c)',
  warm: 'var(--surface-muted, #65535f)',
  dark: 'var(--surface-text, #26131f)',
  white: 'var(--mila-action-ink, #ffffff)',
  card: 'var(--surface-card, #ffffff)',
  line: 'var(--surface-line, #f0c7da)',
  navBg: 'var(--surface-nav, #ffffff)',
};
