// Shared Mila palette. Historical semantic names remain for compatibility, but
// every interactive channel resolves to the same rose signal. Meaning comes
// from copy, iconography, and state — never from a competing accent colour.
export const C = {
  pageBg: 'var(--surface-page, transparent)',
  venus: 'var(--mila-action, #b63d68)',
  venusBright: 'var(--mila-action, #b63d68)',
  venusDeep: 'var(--mila-action-deep, #8d2d50)',
  venusInk: 'var(--mila-action-ink, #ffffff)',
  venusL: 'var(--mila-action-soft, rgba(182,61,104,0.12))',
  danger: 'var(--mila-danger, #8d2d50)',
  dangerL: 'var(--mila-danger-soft, rgba(182,61,104,0.12))',
  rose: 'var(--mila-action, #b63d68)',
  roseL: 'var(--mila-action-soft, rgba(182,61,104,0.12))',
  mercury: 'var(--mila-action, #b63d68)',
  mercuryBright: 'var(--mila-action, #b63d68)',
  mercuryDeep: 'var(--mila-action-deep, #8d2d50)',
  mercuryL: 'var(--mila-action-soft, rgba(182,61,104,0.12))',
  voice: 'var(--mila-action, #b63d68)',
  voiceBright: 'var(--mila-action, #b63d68)',
  voiceL: 'var(--mila-action-soft, rgba(182,61,104,0.12))',
  jupiter: 'var(--mila-action, #b63d68)',
  jupiterBright: 'var(--mila-action, #b63d68)',
  jupiterDeep: 'var(--mila-action-deep, #8d2d50)',
  jupiterL: 'var(--mila-action-soft, rgba(182,61,104,0.12))',
  sage: 'var(--mila-action, #b63d68)',
  sageL: 'var(--mila-action-soft, rgba(182,61,104,0.12))',
  gold: 'var(--mila-action, #b63d68)',
  goldL: 'var(--mila-action-soft, rgba(182,61,104,0.12))',
  purple: 'var(--mila-action, #b63d68)',
  warm: 'var(--surface-muted, #75606a)',
  dark: 'var(--surface-text, #2f1b24)',
  white: 'var(--mila-action-ink, #ffffff)',
  card: 'var(--surface-card, #ffffff)',
  line: 'var(--surface-line, #efd6df)',
  navBg: 'var(--surface-nav, #ffffff)',
};
