// @ts-nocheck
// Generated by Void Manifest Engine
// My Progress

import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

import ProgressChart from '@/components/ProgressChart'
import SkillBreakdown from '@/components/SkillBreakdown'
import AssessmentHistory from '@/components/AssessmentHistory'
import StudyStreakCalendar from '@/components/StudyStreakCalendar'

export default async function ProgressPage() {
  const token = (await cookies()).get('token')?.value
  if (!token) redirect('/login')

  const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000'
  const progress = await fetch(`${baseUrl}/api/progress`).then(r => r.json()).catch(() => [])
  const assessments = await fetch(`${baseUrl}/api/assessments`).then(r => r.json()).catch(() => [])
  const current = await fetch(`${baseUrl}/api/sessions/current`).then(r => r.json()).catch(() => [])

  return (
    <main className="container mx-auto p-4">
      <h1 className="text-2xl font-bold">My Progress</h1>
      <p className="text-gray-600 mt-2">Detailed progress analytics</p>
      <ProgressChart />
      <SkillBreakdown />
      <AssessmentHistory assessments={assessments} />
      <StudyStreakCalendar />
    </main>
  )
}