// @ts-nocheck
// Generated by Void Manifest Engine
// Pronunciation Lab

import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

import PhoneticChart from '@/components/PhoneticChart'
import PhoneticGuide from '@/components/PhoneticGuide'
import WordSearchInput from '@/components/WordSearchInput'
import AudioPlayer from '@/components/AudioPlayer'
import MouthDiagram from '@/components/MouthDiagram'

export default async function PhoneticsPage() {
  const token = (await cookies()).get('token')?.value
  if (!token) redirect('/login')

  return (
    <main className="container mx-auto p-4" style={{maxWidth:560,padding:'24px 20px'}}>
      <h1 className="text-2xl font-bold">Pronunciation Lab</h1>
      <p className="text-gray-600 mt-2">Interactive phonetics and pronunciation</p>
      <PhoneticGuide />
      <PhoneticChart />
      <WordSearchInput />
      <AudioPlayer word="pronunciation" />
      <MouthDiagram sound="/θ/" />
    </main>
  )
}
