// @ts-nocheck
// Generated by Void Manifest Engine
// Pronunciation Lab

import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

import PhoneticChart from '@/components/PhoneticChart'
import WordSearchInput from '@/components/WordSearchInput'
import AudioPlayer from '@/components/AudioPlayer'
import MouthDiagram from '@/components/MouthDiagram'

export default async function PhoneticsPage() {
  const token = (await cookies()).get('token')?.value
  if (!token) redirect('/login')

  const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000'
  const phonetics = await fetch(`${baseUrl}/api/phonetics/:word`).then(r => r.json()).catch(() => [])

  return (
    <main className="container mx-auto p-4">
      <h1 className="text-2xl font-bold">Pronunciation Lab</h1>
      <p className="text-gray-600 mt-2">Interactive phonetics and pronunciation</p>
      <PhoneticChart />
      <WordSearchInput />
      <AudioPlayer />
      <MouthDiagram />
    </main>
  )
}