// @ts-nocheck
// Generated by Void Manifest Engine
// Register new learner

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function POST(request: NextRequest) {
  const body = await request.json()
  // Create user account with learner category, native language, and initial level assessment trigger

  const item = await prisma.user.create({ data: body })
  return NextResponse.json(item, { status: 201 })
}