// @ts-nocheck
// Generated by Void Manifest Engine
// Login

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function POST(request: NextRequest) {
  const body = await request.json()
  // Authenticate user and return JWT token

  const item = await prisma.user.create({ data: body })
  return NextResponse.json(item, { status: 201 })
}