// @ts-nocheck
// Generated by Void Manifest Engine
// Lesson

import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

import LessonContent from '@/components/LessonContent'
import ExercisePlayer from '@/components/ExercisePlayer'
import PhoneticGuide from '@/components/PhoneticGuide'
import VisualAidViewer from '@/components/VisualAidViewer'

export default async function LessonsDetailPage() {
  const token = (await cookies()).get('token')?.value
  if (!token) redirect('/login')

  const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000'
  const lessons = await fetch(`${baseUrl}/api/lessons/:id`).then(r => r.json()).catch(() => [])

  return (
    <main className="container mx-auto p-4">
      <h1 className="text-2xl font-bold">Lesson</h1>
      <p className="text-gray-600 mt-2">Interactive lesson with exercises</p>
      <LessonContent lesson={lessons[0]} />
      <ExercisePlayer exercises={lessons} />
      <PhoneticGuide />
      <VisualAidViewer />
    </main>
  )
}