// @ts-nocheck
// Generated by Void Manifest Engine
// Vocabulary Trainer

import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

import WordCard from '@/components/WordCard'
import SpacedRepetitionTimer from '@/components/SpacedRepetitionTimer'
import PronunciationButton from '@/components/PronunciationButton'
import ProgressRing from '@/components/ProgressRing'

export default async function VocabularyPage() {
  const token = (await cookies()).get('token')?.value
  if (!token) redirect('/login')

  const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000'
  const words = await fetch(`${baseUrl}/api/words`).then(r => r.json()).catch(() => [])

  return (
    <main className="container mx-auto p-4">
      <h1 className="text-2xl font-bold">Vocabulary Trainer</h1>
      <p className="text-gray-600 mt-2">Spaced repetition vocabulary training</p>
      <WordCard word={words[0]} />
      <SpacedRepetitionTimer />
      <PronunciationButton />
      <ProgressRing />
    </main>
  )
}