// Generated by Void Manifest Engine
// DO NOT EDIT BY HAND

export interface User {
  id: number
  email: string
  name: string
  learnerCategory: string
  nativeLanguage: string
  level?: string
  joinDate: Date
  Progresss?: Progress[]
  Assessments?: Assessment[]
  Achievements?: Achievement[]
  StudySessions?: StudySession[]
  createdAt: Date
  updatedAt: Date
}

export interface Lesson {
  id: number
  title: string
  category: string
  learnerLevel: string
  durationMinutes: number
  content: string
  visualAidUrl?: string
  audioUrl?: string
  difficulty: number
  Exercises?: Exercise[]
  Progresss?: Progress[]
  createdAt: Date
  updatedAt: Date
}

export interface Exercise {
  id: number
  lessonId: number
  type: string
  question: string
  correctAnswer: string
  options?: Record<string, any>
  points: number
  hintText?: string
  Lesson?: Lesson
  createdAt: Date
  updatedAt: Date
}

export interface Progress {
  id: number
  userId: number
  lessonId: number
  completed: boolean
  score?: number
  timeSpentSeconds?: number
  mistakes?: Record<string, any>
  lastAttemptDate?: Date
  User?: User
  Lesson?: Lesson
  createdAt: Date
  updatedAt: Date
}

export interface Word {
  id: number
  english: string
  phonetic: string
  translationNative: string
  partOfSpeech: string
  exampleSentence?: string
  audioUrl?: string
  difficultyLevel: number
  learnerCategory: string
  nextReviewDate?: Date
  repetitionCount?: number
  createdAt: Date
  updatedAt: Date
}

export interface Achievement {
  id: number
  userId: number
  badgeName: string
  badgeIcon: string
  description: string
  earnedDate: Date
  category: string
  User?: User
  createdAt: Date
  updatedAt: Date
}

export interface Assessment {
  id: number
  userId: number
  type: string
  score: number
  maxScore: number
  recommendedLevel?: string
  weakAreas?: Record<string, any>
  takenDate: Date
  User?: User
  createdAt: Date
  updatedAt: Date
}

export interface StudySession {
  id: number
  userId: number
  startTime: Date
  endTime?: Date
  lessonsCompleted?: number
  wordsReviewed?: number
  focusArea?: string
  streakDay?: number
  User?: User
  createdAt: Date
  updatedAt: Date
}

// API request/response types