// @ts-nocheck
// Generated by Void Manifest Engine
// Start study session

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function POST(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await request.json().catch(() => ({}))
  const userId = Number(user.sub)
  const current = await prisma.studySession.findFirst({ where: { userId, endTime: null }, orderBy: { startTime: 'desc' } })
  if (current) return NextResponse.json(current)
  const focusArea = typeof body?.focusArea === 'string' ? body.focusArea.slice(0, 80) : null
  const item = await prisma.studySession.create({ data: { userId, startTime: new Date(), focusArea } })
  return NextResponse.json(item, { status: 201 })
}
