// @ts-nocheck
// Generated by Void Manifest Engine
// Start study session

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function POST(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await request.json()
  // Start a new study session, calculate current streak

  const item = await prisma.studySession.create({ data: body })
  return NextResponse.json(item, { status: 201 })
}