// @ts-nocheck
// Generated by Void Manifest Engine
// Get current user

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function GET(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Get current user profile with learner category and level

  const items = await prisma.user.findMany()
  return NextResponse.json(items)
}