// @ts-nocheck
// Generated by Void Manifest Engine
// End study session

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function PUT(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await request.json()
  // End current session, update stats and streak

  const id = Number(request.nextUrl.pathname.split('/').pop() || '0')
  const item = await prisma.studySession.update({ where: { id: Number(id) }, data: body })
  return NextResponse.json(item)
}