// @ts-nocheck
// Generated by Void Manifest Engine
// My Lessons

import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

import LessonList from '@/components/LessonList'
import CategoryFilter from '@/components/CategoryFilter'
import SkillProgressBar from '@/components/SkillProgressBar'

export default async function LessonsPage() {
  const token = (await cookies()).get('token')?.value
  if (!token) redirect('/login')

  const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000'
  const lessons = await fetch(`${baseUrl}/api/lessons`).then(r => r.json()).catch(() => [])
  const progress = await fetch(`${baseUrl}/api/progress`).then(r => r.json()).catch(() => [])

  return (
    <main className="container mx-auto p-4">
      <h1 className="text-2xl font-bold">My Lessons</h1>
      <p className="text-gray-600 mt-2">Lesson browser filtered by category</p>
      <LessonList lessons={lessons} />
      <CategoryFilter />
      <SkillProgressBar />
    </main>
  )
}