// @ts-nocheck
// Generated by Void Manifest Engine
// Achievements

import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

import BadgeGrid from '@/components/BadgeGrid'
import LeaderboardCard from '@/components/LeaderboardCard'
import StreakCounter from '@/components/StreakCounter'

export default async function AchievementsPage() {
  const token = (await cookies()).get('token')?.value
  if (!token) redirect('/login')

  const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000'
  const achievements = await fetch(`${baseUrl}/api/achievements`).then(r => r.json()).catch(() => [])
  const current = await fetch(`${baseUrl}/api/sessions/current`).then(r => r.json()).catch(() => [])

  return (
    <main className="container mx-auto p-4">
      <h1 className="text-2xl font-bold">Achievements</h1>
      <p className="text-gray-600 mt-2">Gamification and achievements</p>
      <BadgeGrid badges={achievements} />
      <LeaderboardCard />
      <StreakCounter />
    </main>
  )
}